// Writes contract ABIs and known deployments into the app as typed TypeScript.
// Usage: npm run export-abis
const fs = require("fs");
const path = require("path");

const ARTIFACTS = path.join(__dirname, "..", "artifacts", "src");
const OUT_DIR = path.join(__dirname, "..", "..", "app", "src", "generated");
const CONTRACTS = {
  fountAbi: "Fount.sol/Fount.json",
  fountTokenAbi: "mocks/FountToken.sol/FountToken.json",
  drawdownRetireAbi: "DrawdownRetire.sol/DrawdownRetire.json",
  feeRouterAbi: "FeeRouter.sol/FeeRouter.json",
  fountRegistryAbi: "FountRegistry.sol/FountRegistry.json",
  fountOracleAbi: "FountOracle.sol/FountOracle.json",
  fountPositionV4Abi: "v4/FountPositionV4.sol/FountPositionV4.json",
};

fs.mkdirSync(OUT_DIR, { recursive: true });

let abis = "// Generated by contracts/scripts/export-abis.js. Do not edit.\n\n";
for (const [name, file] of Object.entries(CONTRACTS)) {
  const { abi } = JSON.parse(fs.readFileSync(path.join(ARTIFACTS, file), "utf8"));
  abis += `export const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
}
fs.writeFileSync(path.join(OUT_DIR, "abis.ts"), abis);

const deployments = {};
const dir = path.join(__dirname, "..", "deployments");
if (fs.existsSync(dir)) {
  for (const f of fs.readdirSync(dir).filter((f) => f === "robinhood.json" || f === "localhost.json")) {
    const d = JSON.parse(fs.readFileSync(path.join(dir, f), "utf8"));
    if (d.network === "hardhat") continue;
    deployments[d.chainId] = d;
  }
}
fs.writeFileSync(
  path.join(OUT_DIR, "deployments.ts"),
  "// Generated by contracts/scripts/export-abis.js. Do not edit.\n\n" +
    `export const deployments: Record<number, Deployment> = ${JSON.stringify(deployments, null, 2)};\n\n` +
    `export type Deployment = {
  network: string;
  chainId: number;
  usdg: \`0x\${string}\`;
  fountToken: \`0x\${string}\`;
  deployer: \`0x\${string}\`;
  timelock: \`0x\${string}\`;
  roles: { admin: \`0x\${string}\`; guardian: \`0x\${string}\`; keeper: \`0x\${string}\` };
  oracle: \`0x\${string}\`;
  feeRouter: \`0x\${string}\`;
  drawdownRetire: \`0x\${string}\`;
  registry: \`0x\${string}\`;
  founts: Record<string, { fount: \`0x\${string}\`; position: \`0x\${string}\`; equityToken: \`0x\${string}\`; name: string }>;
  [key: string]: unknown;
};\n`
);
const config = require("../config/robinhood.json");
const catalog = {
  chainId: config.network.chainId,
  usdg: config.tokens.usdg.address,
  equityTokens: Object.fromEntries(
    Object.entries(config.equityTokens).map(([t, v]) => [t, { name: v.name, address: v.address }])
  ),
  launchFounts: config.launch.founts,
  oracle: config.oracle,
  heldValueCapUsdg: config.launch.heldValueCapUsdg,
};
fs.writeFileSync(
  path.join(OUT_DIR, "catalog.ts"),
  "// Generated by contracts/scripts/export-abis.js. Do not edit.\n\n" +
    `export const catalog = ${JSON.stringify(catalog, null, 2)} as const;\n`
);

console.log(`Exported ${Object.keys(CONTRACTS).length} ABIs and ${Object.keys(deployments).length} deployment(s) to ${OUT_DIR}`);
